// Stamps a unique build version into BOTH a static file the client polls
// (public/version.json) and a constant baked into the bundle (src/buildVersion.ts).
// Because they're written together, a deployed bundle always knows its own version,
// and an OLD bundle running in a browser will see version.json change and force a
// reload to the latest — so only the newest version stays accessible.
import { writeFileSync } from "node:fs";

const version = `${Date.now()}`;

writeFileSync("public/version.json", JSON.stringify({ version }) + "\n");
writeFileSync(
  "src/buildVersion.ts",
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\nexport const BUILD_VERSION = "${version}";\n`,
);

console.log("build version:", version);
